// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RefillingStation.Api.Data;

#nullable disable

namespace RefillingStation.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260311141741_AddPaidQtyActualToTrip")]
    partial class AddPaidQtyActualToTrip
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.4");

            modelBuilder.Entity("RefillingStation.Api.Entities.Trip", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("CashCollectedActual")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("CashUsed")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("CollectedQty")
                        .HasColumnType("TEXT");

                    b.Property<string>("CustomerType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("DeliveredQty")
                        .HasColumnType("TEXT");

                    b.Property<string>("Employee")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("EstimatedCash")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("FreeQty")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PaidQtyActual")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PricePerGallon")
                        .HasColumnType("TEXT");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ToBePaidQty")
                        .HasColumnType("TEXT");

                    b.Property<int>("TripNumber")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TripType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Trips");
                });
#pragma warning restore 612, 618
        }
    }
}
