// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RefillingStation.Api.Data;

#nullable disable

namespace RefillingStation.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260323133806_UpdateTripModel")]
    partial class UpdateTripModel
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.4");

            modelBuilder.Entity("RefillingStation.Api.Entities.CustomerDebtEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Amount")
                        .HasColumnType("TEXT");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("EntryType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("RelatedTripId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("CustomerDebtEntries");
                });

            modelBuilder.Entity("RefillingStation.Api.Entities.Expense", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Amount")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("ExpenseCategory")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Expenses");
                });

            modelBuilder.Entity("RefillingStation.Api.Entities.PayrollEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("AdvanceDeduction")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("AdvanceGiven")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("CashPaid")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("EmployeeName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("SalaryAmount")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("PayrollEntries");
                });

            modelBuilder.Entity("RefillingStation.Api.Entities.Trip", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("ActualCashCollected")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ActualPaidQty")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("CollectedQty")
                        .HasColumnType("TEXT");

                    b.Property<string>("CustomerCategory")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("DeliveredQty")
                        .HasColumnType("TEXT");

                    b.Property<string>("EmployeeName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("FreeQty")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsRemitted")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("LoadedQty")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int?>("RelatedTripId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("ReplacementQty")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ReturnedQty")
                        .HasColumnType("TEXT");

                    b.Property<string>("Segment")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("TimeEnded")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("TimeStarted")
                        .HasColumnType("TEXT");

                    b.Property<int>("TripNumber")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TripType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Trips");
                });
#pragma warning restore 612, 618
        }
    }
}
